[package]
name = "nvcap_calculator"
version = "0.1.0"
authors = ["Avery Black <avery.c.black@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
chrono = "0.4"
ctrlc = "3.2.0"